DEBUG 2021-03-24 12:16:34.006 UTC: 	 CRAB Client version: v3.210127
DEBUG 2021-03-24 12:16:34.007 UTC: 	 Running on: Linux lxplus745.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-03-24 12:16:34.007 UTC: 	 Executing command: 'submit'
DEBUG 2021-03-24 12:16:34.013 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wangz/.crab3
INFO 2021-03-24 12:16:34.040 UTC: 	 Will use CRAB configuration file crabuser.py
DEBUG 2021-03-24 12:16:34.041 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-03-24 12:16:34.345 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-03-24 12:16:34.404 UTC: 	 Working area '/afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/sl7/CMSSW_10_2_18/src/DarkPhotonAnalysisV2/DimuonAnalysis/crab/crab_projects/crab_ntuple_1GeV_2' already exists 
Please change the requestName in the config file
ERROR 2021-03-24 12:16:34.404 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/ClientUtilities.py", line 402, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/sl7/CMSSW_10_2_18/src/DarkPhotonAnalysisV2/DimuonAnalysis/crab/crab_projects/crab_ntuple_1GeV_2' already exists 
Please change the requestName in the config file
INFO 2021-03-24 12:16:34.410 UTC: 	 Log file is /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/sl7/CMSSW_10_2_18/src/DarkPhotonAnalysisV2/DimuonAnalysis/crab/crab.log
DEBUG 2021-03-24 14:23:12.533 UTC: 	 CRAB Client version: v3.210127
DEBUG 2021-03-24 14:23:12.533 UTC: 	 Running on: Linux lxplus745.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-03-24 14:23:12.533 UTC: 	 Executing command: 'submit'
DEBUG 2021-03-24 14:23:12.534 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wangz/.crab3
INFO 2021-03-24 14:23:12.534 UTC: 	 Will use CRAB configuration file crabuser.py
DEBUG 2021-03-24 14:23:12.535 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-03-24 14:23:12.575 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-03-24 14:23:12.575 UTC: 	 Working area '/afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/sl7/CMSSW_10_2_18/src/DarkPhotonAnalysisV2/DimuonAnalysis/crab/crab_projects/crab_ntuple_1GeV_2' already exists 
Please change the requestName in the config file
ERROR 2021-03-24 14:23:12.575 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/ClientUtilities.py", line 402, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/sl7/CMSSW_10_2_18/src/DarkPhotonAnalysisV2/DimuonAnalysis/crab/crab_projects/crab_ntuple_1GeV_2' already exists 
Please change the requestName in the config file
INFO 2021-03-24 14:23:12.645 UTC: 	 Log file is /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/sl7/CMSSW_10_2_18/src/DarkPhotonAnalysisV2/DimuonAnalysis/crab/crab.log
